baseurl: "https://melitix.com/"
title: "Melitix Events"
canonifyurls: true
paginate: 3

theme: "hugo-theme-lean-launch-page"

googleAnalytics: "G-GR639DK1WC"

params:
  tagline: "A modern events platform coming soon"
  mailchimpURL: "https://melitix.us22.list-manage.com/subscribe/post?u=fe896ef5a18ba018ca43aa978&amp;id=b9fbfc1654&amp;f_id=0075c2e1f0"
